services:
  hlds-gameserver:
    env_file: .env
    ulimits:
      # Truncated core dumps fix
      core:
        soft: 1073741824 # 1GB
        hard: 1073741824 # 1GB
    ports:
      - $PORT:$PORT/udp
    expose:
      - $PORT/udp
    build:
      context: .
    #image: hldsdocker/rehlds-cstrike:regamedll
    entrypoint: "./hlds_run"
    volumes:
      - ./configs/plugins.ini:/home/hlds_user/hlds/cstrike/addons/amxmodx/configs/plugins.ini
      - ./configs/cmdaccess.ini:/home/steam/cstrike/cstrike/addons/amxmodx/configs/cmdaccess.ini
      - ./configs/users.ini:/home/steam/cstrike/cstrike/addons/amxmodx/configs/users.ini
      - ./configs/maps.ini:/home/hlds_user/hlds/cstrike/addons/amxmodx/configs/maps.ini
      - ./configs/amxx.cfg:/home/hlds_user/hlds/cstrike/addons/amxmodx/configs/amxx.cfg
      - ./configs/modules.ini:/home/hlds_user/hlds/cstrike/addons/amxmodx/configs/modules.ini
      - ./configs/gamemode_deathmatch.json:/home/hlds_user/hlds/cstrike/addons/amxmodx/configs/redm/gamemode_deathmatch.json
      - ./configs/yapb.cfg:/home/hlds_user/hlds/cstrike/addons/yapb/conf/yapb.cfg
      - ./configs/maps.ini:/home/hlds_user/hlds/cstrike/mapcycle.txt
      - ./configs/server.cfg:/home/hlds_user/hlds/cstrike/server.cfg
      - ./configs/motd.txt:/home/hlds_user/hlds/cstrike/motd.txt
    command:
      [
        '-debug -game cstrike -bots -pingboost $PINGBOOST +ip 0.0.0.0 -port $PORT +map $MAP -maxplayers $MAXPLAYERS +sv_lan $SV_LAN +rcon_password "$RCON_PASSWORD" +hostname "$SERVER_NAME"',
      ]
